### ISSUE TITLE
wrapping entire hunks with @media breaks @media queries or @font-face

### ISSUE THREAD

**Issue by carljm** [mintchaos/django_compressor#15]
Currently, if you link CSS in your template using media attributes, compressor creates a single bundle and wraps the entire contents of those CSS files in @media screen { ... } @media print { ... }. This is a problem, because you can't nest @ declarations (according to this article http://www.css-zibaldone.com/articles/syntax/css-syntax.html it is illegal CSS syntax and most browsers reject it, though IE accepts it; in my experience with @font-face, it's IE and FF that reject it). So if some of those CSS files contain @media selectors or @font-face declarations internally, those are broken in the bundle, at least in many browsers.

IMO as these techniques become more common, this means the @media-wrapping as compressor does it now is not an option any longer.

Issue #6 also brings up that there are performance reasons to prefer per-media bundles rather than a single bundle, to avoid unnecessary downloads.

My proposal is that compressor should stop wrapping CSS content with @media, and instead create one bundle per media attribute value found, linking those bundles using the same media attribute value. I'll work on this; I think the implementation is pretty straightforward. Any concerns in principle?

**Comment by carljm** [comment]
I have this implemented, tested and working great in my no_media_wrappers branch: http://github.com/carljm/django_compressor/commits/no_media_wrappers

**Comment by jezdez** [comment]
Fixed in 55acb2da0602776a387c27cd294150b50da52c39.

**Comment by mintchaos** [comment]
Reopening this because it needs a bit more thought. Right now it splits up multiple media declaration into separate files. Which is great. but the fatal flaw here is that now compressed CSS is possibly in a different order than the original CSS, which is biting us on some of our sites right now.

Things are broken that we never touched and it took a bit to trace it back to compressor rearranging our CSS.

For example if something was defined in a media=all stylesheet, and then overridden in a media=screen stylesheet, it easily break the sites in a way that can't be seen with debug off. Which goes against the principle of least surprise and is a bug IMO. CSS depends way too much on order for computers to be making decisions about it.

So, possible solutions:
- Keep generating multiple CSS files but generate a new one every time media type changes in the document order. (it puts it on the document authors to keep their media types sorted). 
- Make an setting to go back to the single file with (annoying for the reasons listed above)

Any other thoughts or solutions?

**Comment by carljm** [comment]
I think the first option is what needs to happen. Correctness (not changing the behavior of the CSS) has to take priority over generating fewer files. Adding a "which subtly broken behavior do you prefer?" setting is just nasty. 

Not sure how hard the fix would be, I'll look into it.

**Comment by mintchaos** [comment]
Yeah, I think the first one is better. I'll take less compressed media over media that breaks sites everyday. Interested to see if Jannis has any thoughts.
